### ISSUE TITLE
[Feature Request] Reorganization : Split Aplication into Advanced and Basic tabs

### ISSUE THREAD

**Issue by alsa64** [ptrsuder/crop-upscale-merge#1]
The advanced tab would hold functions to be used by power-users who would like more control, while the Basic tab, would hide advanced settings choosing sane defaults for the user.

**Comment by victorca25** [comment]
For the power-users, the 2nd step could mean using a series of models before merging back or even other architectures besides ESRGAN, for example, BasicSR or even pix2pix and CycleGAN or others that also suffer from VRAM limitations. Decoupling from the ESRGAN folder structure and allowing for custom scripting in this step would make the tool even more flexible to use

**Comment by ptrsuder** [comment]
Second tab created. Added ability to change paths to all major folders for now.
