### ISSUE TITLE
Weird behaviour

### ISSUE THREAD

**Issue by CreeperLava** [ptrsuder/crop-upscale-merge#10]
I put the following pictures in the LR folder :
[esrgan.zip](https://github.com/ptrsuder/crop-upscale-merge/files/3188915/esrgan.zip)

Then I hit the crop button, pictures disappeared from the LR folder, but no tiles appeared anywhere. Then the program froze once I hit "Run ESRGAN", so I assume something went wrong in the crop part :
![crop-upscale-merge_2019-05-16_20-14-30](https://user-images.githubusercontent.com/12874678/57884674-7bf29b00-7829-11e9-8ec3-8e33e3494337.png)

I tried to change the tiling mode in the settings, didn't change anything. Not quite sure what's going on here. Also tried changing "overwrite" to "tiles". Not sure what that's supposed to do, but it didn't change anything.

**Comment by ptrsuder** [comment]
You supposed to put images in another folder, the one that is called "images" in settings.

**Comment by CreeperLava** [comment]
Ah, I see. So I did that, however I am having another freeze after hitting "Run ESRGAN". The tiles are in the LR folder, yet I see no CPU or GPU activity and the GUI is unresponsive.

![crop-upscale-merge_2019-05-19_23-21-06](https://user-images.githubusercontent.com/12874678/57988303-dd667400-7a8c-11e9-8b76-80a3b2a22016.png)
