### ISSUE TITLE
Max tile settings don't always persist

### ISSUE THREAD

**Issue by CreeperLava** [ptrsuder/crop-upscale-merge#13]
For some reason, changing the "max tile" settings, closing the window and opening it again resets the settings to their previous value. I say "not always", because at some point I managed to change them. I believe they persisted after I ran a successful ESRGAN batch. Tiling mode has the same problem. Path settings work fine though. Here is a 3 step guide.

1. Open the settings menu
![crop-upscale-merge_2019-06-01_17-13-01](https://user-images.githubusercontent.com/12874678/58750288-acc10a00-8490-11e9-9006-00520c27ca10.png)
2. Change the settings
![crop-upscale-merge_2019-06-01_17-13-08](https://user-images.githubusercontent.com/12874678/58750289-ad59a080-8490-11e9-93a4-d4e1345a279c.png)
3. Close and reopen the tool
![crop-upscale-merge_2019-06-01_17-13-16](https://user-images.githubusercontent.com/12874678/58750290-ad59a080-8490-11e9-86e9-3c263c7047db.png)

**Comment by ptrsuder** [comment]
Right now settings are saved at the start of every operation (crop, run esrgan, merge, run all).

**Comment by CreeperLava** [comment]
Just tried 0.9.55, the problem remains.

**Comment by ptrsuder** [comment]
The value of width * height is all that matters. Width and height values are not saved.

**Comment by CreeperLava** [comment]
Is that really a good idea ? I want 600x600 tiles, not 900x400. That way 512x512 textures aren't split in 2.

**Comment by ptrsuder** [comment]
360 000 < 512 * 512, so it won't be split in 2

**Comment by CreeperLava** [comment]
Even if 400 < 512 ? I see, in that case it's less of a problem. Still a bit unclear, but alright
