### ISSUE TITLE
[Feature Request] Save scale for each model

### ISSUE THREAD

**Issue by alsa64** [ptrsuder/crop-upscale-merge#7]
When a model is first used ask the user for the scale. 
The default should be 4.
It should try to guess the scale from the file name.
If that fails ask the user.
It should then test the scale if it is correct. (upscale a small image with the guessed scale, then try 4, 1, 2, 8, 16) in that order, if that fails inform the user and give him a chance to try a different scale.)

**Comment by ptrsuder** [comment]
Obsolete. Model upscale size now is automatically detected.
